### ISSUE TITLE
Wall Logic: Numbers remain grey even after exiting Trial Mode

### ISSUE THREAD

**Issue by edderiofer** [robx/pzprjs#103]
On Wall Logic, ensure the "Grey each correct number" option is checked. Then, turn on Trial Mode and satisfy any clue, and then Reject trial. The clue remains grey, as if it's been satisfied, and needs to be clicked twice to be ungreyed.

The same problem happens after making a move that satisfies a clue, and then undoing said move.

**Comment by robx** [comment]
Thanks for the report. I can't reproduce this; what's your browser/OS? Does it also happen with other combinations?

**Comment by edderiofer** [comment]
I'm on Chrome 78.0.3904.97, Windows 10 64-bit. This also happens on Firefox 70.0.1, Windows 10 64-bit, as well as Safari, iOS 12.4.

A bit more information about the bug; it seems to only happen if undoing/rejecting trial doesn't change the number of arrows extending from said clue. So, for instance, drawing a length-two arrow down from the top left 3 clue [here](https://puzz.link/p?walllogic/10/10/g3+j6l6m+j7+j2h2h2g3g+g1h3i6m7+h1n4k4g2i1g4j5i6i) and then a length-one left won't trigger the bug when undoing, but drawing a length-three arrow down will keep the 3 clue greyed when undoing twice (and then ungrey it on the third undo).

**Comment by robx** [comment]
Yes, I see it too in that case, thanks!

Also redoing thrice doesn't grey the clue although it should.
