### ISSUE TITLE
Compass: visual bug when erasing clues

### ISSUE THREAD

**Issue by montelucci** [robx/pzprjs#111]
In Compass edit mode, when erasing a clue the east number stays on screen.

A right-click on this:
<img width="96" alt="compass1" src="https://user-images.githubusercontent.com/6699059/72210618-5acc7200-34be-11ea-8abd-4f8c3e60c5a5.png">

produces this:
<img width="93" alt="compass2" src="https://user-images.githubusercontent.com/6699059/72210623-6324ad00-34be-11ea-832a-0d3b43640729.png">

The bug is only visual: the answer checker and the exported URL work as intended.

**Comment by robx** [comment]
Thanks for the report, confirmed. Curiously, "Repaint whole board" doesn't make it disappear.
