### ISSUE TITLE
Slalom judge bug

### ISSUE THREAD

**Issue by domishana** [robx/pzprjs#120]
https://puzz.link/p?slalom/d/5/4/911152225111422h12h/0

This puzzle has no solution. But, incorrect answer is judged "correct"(See below picture).
![image](https://user-images.githubusercontent.com/29448240/73325956-ccb10380-4293-11ea-83c1-cbecb366c648.png)

**Comment by robx** [comment]
Thanks for the report! Fixed version should be live now.
