### ISSUE TITLE
Double Back: loop can be drawn over black cells.

### ISSUE THREAD

**Issue by edderiofer** [robx/pzprjs#125]
As per the title. See image below.
![image](https://user-images.githubusercontent.com/16442480/73387364-5e3a6880-42c8-11ea-8c0c-cab2dd1ff252.png)

https://puzz.link/p?doubleback/10/10/080g1040g10004080000000eb000000000000g8041gg420210480011 (Source: https://twitter.com/potechi1104/status/1222427518881296384)

**Comment by robx** [comment]
Funny, thanks!
