### ISSUE TITLE
Herugolf: clearing the puzzle and undoing generates weirdness

### ISSUE THREAD

**Issue by edderiofer** [robx/pzprjs#126]
As per the title. See below image. To reproduce, draw any bent line from a ball, clear the puzzle, and undo.
![image](https://user-images.githubusercontent.com/16442480/73387786-f89aac00-42c8-11ea-829e-36d16d51c092.png)

https://puzz.link/p?herugolf/10/10/000000000000000000009r6n6zphzohihxho4i (Source: https://twitter.com/potechi1104/status/1222442659177848832)

**Comment by robx** [comment]
ACK, thanks for the report!

**Comment by x-sheep** [comment]
I wonder why the prehooks are able to prevent operations when undoing. I think it's safe to always perform an undo or redo, since those operations have been validated already.

It might be a good idea to list all puzzles with prehooks, to see if this change could cause problems anywhere.

**Comment by robx** [comment]
I'm a little bit lost (I guess you've tracked the bug down to the prehooks?), but the argument makes sense. I would be willing to risk making that change anyway.
