### ISSUE TITLE
Generic Nonstandard Grid Shapes

### ISSUE THREAD

**Issue by jeffreybardon** [robx/pzprjs#128]
Some genres such as Fivecells, Spiral Galaxies, and Double Back allow for marking some cells in the bounding box of the puzzle as cells that are not part of the puzzle. Others, such as Kakuro, Akari, and Castle Wall have a built-in idea of a "wall" cell. It would be nice to have this more consistent across genres and allow for non-rectangular grids in more types.

**Comment by robx** [comment]
I agree that this would be nice, but it would require significant changes and I don't see those happening any time soon. Happy to assist if someone wants to implement this, but closing for the moment.
