### ISSUE TITLE
fillomino: number graph is not updated when using Erase data

### ISSUE THREAD

**Issue by montelucci** [robx/pzprjs#155]
e.g. open https://puzz.link/p?type=player&pzprv3/fillomino/3/3/.%20.%20.%20/.%20.%20.%20/.%20.%20.%20/9%209%209%20/9%209%209%20/9%209%201%20/0%200%20/0%200%20/0%200%20/0%200%200%20/0%200%200%20//
Select Erase data, erase the 1, click Check: "A number is bigger than the size of block." (should be Complete)
Now erase some or all 9s, click Check: same (note the red cells)

**Comment by montelucci** [comment]
nanro has the same behavior

**Comment by robx** [comment]
Confirmed.

**Comment by x-sheep** [comment]
This has been fixed for Fillomino, but not for Nanro.
