### ISSUE TITLE
consider ending all urls in / (slash) to avoid link sharing trouble with trailing . (full stop)

### ISSUE THREAD

**Issue by robx** [robx/pzprjs#159]
When pasting a link that ends in `.` on discord, it links to the URL without the final dot erroneously. We could work around that by ensuring that URLs don't end in `.` by appending a `/`; simplest would be to add it regardless of whether the previous last character is a `.`. I believe there's no puzzle types where this would cause trouble.

**Comment by x-sheep** [comment]
Does this still occur? I believe that this was solved years ago by appending a slash when the last character is not alphanumeric.

**Comment by robx** [comment]
> Does this still occur? I believe that this was solved years ago by appending a slash when the last character is not alphanumeric.

I think you're right, this is fixed in our fork of pzprjs. I'll file a follow-up issues against the database to consider fixing "legacy" URLs (e.g. Akari generated with pzv.jp) there.
