### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by robx** [robx/pzprjs#16]
This is to collect issues with the English translation.

**Comment by x-sheep** [comment]
dbchoco: Nikoli has just added an [english rule page](https://www.nikoli.co.jp/en/puzzles/double_choco.html) where the name is translated as "Double Choco" instead of "Double Chocolate". pzprjs should probably use the new official name.

**Comment by x-sheep** [comment]
In answer.js:1096
`csDivide: ["黒マスが分断されています。", "The shaded cells are divided,"],`

The sentence should not end with a comma.

**Comment by robx** [comment]
@x-sheep: fixed that one, thanks!

This issue doesn't seem to be useful, closing.
