### ISSUE TITLE
Renban: "consecutive numbers" rule isn't checked until all cells are filled, even with "check multiple errors" on.

### ISSUE THREAD

**Issue by edderiofer** [robx/pzprjs#162]
In the puzzle below, put a 9 and a 16 in the L-shaped region with a 7. Instead of giving the error "The numbers in the room are not consecutive.", the interface instead gives the error "There is an empty cell.". This is still true even when "check multiple errors" is on.

https://puzz.link/p?renban/6/6/hdbqma7j1bj6bic9hai4hb7m5j7g7ia

![image](https://user-images.githubusercontent.com/16442480/76136216-14f7da00-6027-11ea-8dc9-fd7eafb48e20.png)

**Comment by robx** [comment]
fixed, thanks
