### ISSUE TITLE
broken popup-moving on touchscreen

### ISSUE THREAD

**Issue by robx** [robx/pzprjs#169]
As reported on chat:

X_Sheep: Moving a popup is broken on both Safari on iOS and Chrome for Android, although they misbehave in different ways. This means that solving a puzzle by inputting numbers using the panel is nearly impossible.

X_Sheep: This also happens on pzv.jp.

X_Sheep: yes, on iPhone I can move it horizontally, but going down slightly will change the movement to a scroll

X_Sheep: if the puzzle is too large and horizontal scroll bars are enabled, I can't move the popup in any direction without going into a scroll

**Comment by glasser** [comment]
I'm seeing this these days. (Maybe it's time for me to learn more about touch events on mobile and try to fix it myself.)
