### ISSUE TITLE
Haisu cross marks with one-button input

### ISSUE THREAD

**Issue by boboquack** [robx/pzprjs#197]
Using one-button input to draw a cross on a Haisu doesn't seem to delete a segment underneath if it exists. Right-clicking to enter a cross does delete the underlying segment, however.

**Comment by boboquack** [comment]
Also appears to happen on nagareru loop

**Comment by robx** [comment]
Hmm I can't reproduce this (also I can't find one-button mode for nagareru loop). Can't really have been fixed since you commented, could you perhaps provide some step by step instructions to show this?

**Comment by robx** [comment]
Closing, feel free to reopen with more details.
