### ISSUE TITLE
Haisu allows to input big numbers

### ISSUE THREAD

**Issue by u-ndefine** [robx/pzprjs#199]
The Haisu editor allows to input big numbers up 999.
To do this, right click an empty, selected cell.
**Solution:** Use the `math.ceil(board's number of cells/2)`

![image](https://user-images.githubusercontent.com/41176671/82722689-8d536a80-9cfb-11ea-807e-7095540a0594.png)

**Comment by boboquack** [comment]
I feel like this is not really an issue because it's akin to putting a white cell in a corner in a Masyu: clearly wrong but it's the constructor's fault.

**Comment by robx** [comment]
Not a major issue, but we have infrastructure available to deal with things like this, and most puzzles calculate a reasonable upper bound. So I'll leave this open, and patches welcome!
