### ISSUE TITLE
Advice of Slalom puzzles

### ISSUE THREAD

**Issue by psml-imeji** [robx/pzprjs#206]
Allow users edit the number in the circle of the Slalom so we can make puzzles like [that](https://puzz.link/p?slalom/d/5/5/911162611152424l/0).

**Comment by robx** [comment]
That looks like a broken puzzle. Would you explain what you mean here?

**Comment by psml-imeji** [comment]
> That looks like a broken puzzle. Would you explain what you mean here?

The number in the circle is fixed as the amount of gates, and I want to let it able to change the number in the circle so I can make this puzzle solveable.

**Comment by robx** [comment]
But there's also a rule "There is a gate that the line is not passing.": https://puzz.link/rules.html?slalom If I understand correctly that would fail for your suggested puzzle anyway.

Can you show such puzzles in the wild? What are the original Nikoli rules for the type?

**Comment by robx** [comment]
I found this: http://www.nikoli.co.jp/en/puzzles/suraromu.html The rules seem correct as they are.

**Comment by psml-imeji** [comment]
> I found this: http://www.nikoli.co.jp/en/puzzles/suraromu.html The rules seem correct as they are.

Ok......
