### ISSUE TITLE
Make Sudoku marks works like the other Sudoku apps!

### ISSUE THREAD

**Issue by psml-imeji** [robx/pzprjs#207]
In the puzz.link it can only place 4 marks on each cell, and can only be placed on the corners, which other apps can place any marks you want and will placed based on the number.
Like this site: https://www.sudokuwiki.org/sudoku.htm

**Comment by robx** [comment]
I agree that the pencil mark feature isn't great, though I'm not sure I like the kind of pencil marks you mention either. Personally I like the free text field as in fed-sudoku.

Moving this over to the catch-all issue #1.
