### ISSUE TITLE
Large "undefined" appears in Easy as ABC

### ISSUE THREAD

**Issue by edderiofer** [robx/pzprjs#212]
As per the title. Open up any Easy as ABC puzzle, and the word "undefined" appears at the top left of the grid. The same also extends to the rules page.

**Comment by x-sheep** [comment]
@robx Could be related to the removal of this line: https://github.com/robx/pzprjs/pull/190/files#diff-231925904b92554579fffb5bf4405f44L648

**Comment by robx** [comment]
Yeah I think that was it (combined with the weird hacky `Indicator` excell that easyasabc uses, and its custom `getex` that always returns this indicator. Made the indicator not display text, which seems like not a very good fix but it works...
