### ISSUE TITLE
fillomino: Change AreaNumBlockGraph

### ISSUE THREAD

**Issue by x-sheep** [robx/pzprjs#222]
https://github.com/robx/pzprjs/issues/1#issuecomment-475914799

I've looked into implementing auto-placing borders around polyominoes with the correct amount of numbers. Fillomino's answer checker currently uses AreaNumBlockGraph, which groups different numbers together in the same area if they have empty cells between them. I can see three possible solutions to adding a new graph which only groups identical numbers, each of them less than ideal:

## 1. Make the new graph independent of AreaNumBlockGraph
This makes the answer check ignore these implicit lines completely.

## 2. Attempt to change AreaNumBlockGraph into a multi-level graph
Calculating the edges for AreaNumBlockGraph would depend on the new graph being up to date. This might result in the graph being completely rebuilt every time a certain move is made.

## 3. Replace AreaNumBlockGraph and force all cells to contain a number
This is the easiest solution, but also the most disruptive to the current solver. Drawn border lines will become entirely cosmetic, save for a simple check that looks for identical numbers separated by a border. This also removes support for answer-checking cells with a question mark (I still wonder why question marks exist in this type...)

**Comment by robx** [comment]
Sorry for replying to the tangential question first, but...

> I still wonder why question marks exist in this type...

I believe that question marks in general exist primarily as a place-holder for the constructor. If we weren't sort of tied to what exists out there right now, I'd be in favour of disallowing question marks entirely for player links for most types, and dropping any sophisticated answer check handling.

**Comment by robx** [comment]
Regarding the issue as such (or the interface improvement suggestion you're referencing), I'd rather see a more fundamental rework of the Fillomino solver. Particularly, I'd like to consider whether it's possible to make number entry optional (so e.g. an empty 1x1 with four borders would pass the answer check), and whether we can make use of the aux lines (which probably shouldn't be aux anymore then) when building the graph. I know croco-puzzle used to have a nice hybrid solving interface, where all of numbers, skeleton lines and walls could be entered.

**Comment by x-sheep** [comment]
Okay, that aligns more with solution 2. Changing qsubs to lines would make sense.

Fillomino should use the following graphs, which have to be updated in this order:

1. A graph which uses cells with lines (formerly qsubs) as edges. A group of cells which has one type of number, should add "ghost numbers" to the empty cells (possibly using qcmp? I don't know if it can have values other than 0 and 1)

2. A graph which connects only identical numbers, excluding numbers with a user-added border between them. This should combine question numbers, answer numbers and ghost numbers. If a group has the correct size, it should add "ghost borders" around itself.

3. The original AreaNumBlockGraph, updated to check for ghost borders as well as manual borders and adjacent cells with different numbers. Finally, the check for areas without numbers is removed.

The interface should draw grey lines for ghost borders and between cells with different numbers. We can also try out different styles for drawing ghost numbers.

**Comment by x-sheep** [comment]
This has now been implemented with the merge with pzprxs.
