### ISSUE TITLE
Factors: Output link is not right

### ISSUE THREAD

**Issue by psml-imeji** [robx/pzprjs#228]
See the file, open it in the editor and output the link to see the bug.
[factors.txt](https://github.com/robx/pzprjs/files/5540237/factors.txt)

**Comment by x-sheep** [comment]
Is this still an issue? I see no difference between the puzzle when loaded from the text file, and when exporting the URL. Duplicating the board also results in no visible problems.

**Comment by psml-imeji** [comment]
It seems fixed.
