### ISSUE TITLE
New puzzle type: Ovotovata

### ISSUE THREAD

**Issue by EricFox53** [robx/pzprjs#232]
Hello! I'd like to suggest that Ovotovata be added as a genre. This is a genre of my own creation from a few months ago.

Draw a single non-intersecting loop through the centers of some cells so that all shaded regions are visited. When the loop exits a numbered region in any direction, it must travel in a straight line for the indicated number of cells, and then turn.

Here are some example puzzles by me (Eric Fox):
https://tinyurl.com/yxhazldy
https://tinyurl.com/yxgrl6aw
https://tinyurl.com/y3k53abs
https://tinyurl.com/y2aqoq5b

For the first two puzzles, pretend all the regions are shaded. These ones were made before that adjustment to the rules.
The last puzzle demonstrates unshaded regions and ? clues.

Thanks!

**Comment by x-sheep** [comment]
I'm not sure I understand the rules. Can you provide the solution for one of these puzzles?

**Comment by EricFox53** [comment]
> I'm not sure I understand the rules. Can you provide the solution for one of these puzzles?

Sure, here's the solution to the first puzzle.
https://imgur.com/a/MFsyV6w

**Comment by x-sheep** [comment]
Thanks. I didn't realize that the number 1 means that the turn is adjacent to the region it exists.
