### ISSUE TITLE
nanro accepts solutions containing circles

### ISSUE THREAD

**Issue by madewokherd** [robx/pzprjs#246]
This is considered a valid solution:
https://puzz.link/p?type=player&pzprv3/nanro/3/2/2/0%200%20/0%201%20/0%201%20/.%20.%20/.%20.%20/.%20.%20/1%20.%20/%2B%202%20/.%202%20//

It probably shouldn't be.

**Comment by edderiofer** [comment]
IMO, Nanro *should* accept solutions containing circles, but not like this. Ideally, the interface should count how many cells in a region are circles or numbers, then treat all circles as if they were that count.

**Comment by Riverness** [comment]
Just ran into a similar situation:

https://puzz.link/p?type=player&pzprv3/nanro/5/5/6/0%200%201%201%201%20/0%200%201%201%201%20/2%203%203%201%204%20/2%205%203%203%204%20/2%205%205%203%204%20/.%20.%20.%203%203%20/.%203%20.%20.%20.%20/.%205%20.%20.%20.%20/.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20/3%203%20-%20.%20.%20/.%20.%20-%20-%203%20/3%20.%205%20-%201%20/3%20-%205%205%20%2B%20/3%201%20-%205%20-%20//
