### ISSUE TITLE
Slitherlink Help Rules should state the rules’

### ISSUE THREAD

**Issue by abaljeu** [robx/pzprjs#259]
In fact it only shows example errors, but never what should be done.

**Comment by robx** [comment]
What should be done can be inferred from the errors, though. That's just how the rules are implemented, and I'm rather fond of the approach -- it's impossible for the written rules to disagree with the implementation this way.

However, your wish might be adressed when the changes from pzprxs make it over here. (#271)

**Comment by x-sheep** [comment]
All puzzle types now have written rules. Here are the rules for Slitherlink: https://puzz.link/rules.html?slither
