### ISSUE TITLE
LITS puzzles no longer filling empty squares with green when room completed

### ISSUE THREAD

**Issue by jrunning** [robx/pzprjs#260]
Previously after placing four black squares in a room in a LITS puzzle the remaining squares would automatically be shaded green, which was a nice indicator of a "finished" room. Sometime in the past few weeks this changed on the puzz.link site.

Here's a GIF of the current behavior:

![Screen Recording 2022-05-26 at 1 27 53 PM](https://user-images.githubusercontent.com/117983/170552779-202595d5-0ec8-4756-8c63-9363e66fd2d9.gif)

Previously after placing the fourth black square, the remaining square in the room would have been shaded green.

**Comment by robx** [comment]
might you have unchecked "Paint background of each completed block" accidentally?

**Comment by jrunning** [comment]
@robx Yep, that was it. My mistake!
