### ISSUE TITLE
deployment: automatically purge cloudflare cache

### ISSUE THREAD

**Issue by robx** [robx/pzprjs#272]
When puzz.link is redeployed with a new version of pzprjs, we should probably purge the cloudflare cache to ensure new versions of p.html and the javascript files are served.

(I'm not entirely sure to what extent things are fine right now, and we'll just keep serving stale but functional-as-previously content for old puzzles, or whether there'll be actual trouble if the HTML structure of p.html changes.)

**Comment by x-sheep** [comment]
I remember major issues every time a version mismatch occured between p.html and the scripts, so I think it's better to fix this before merging pzprxs and resuming regular updates.

**Comment by robx** [comment]
I've implemented this, though chances are it's purging a bit too eagerly now... Guess we'll see how it goes.

An alternative to purging the cache might be to serve versioned javascript files, i.e., instead of `p.html` referencing `js/pzpr.js?<hash>`, have it reference `js/<hash>/pzpr.js` and keep serving the old copies for a while. Then it'd be safe to keep stale copies of `p/<type>/<data>` cached for a bit -- the only effect would be that e.g. bug fixes don't make it to cached puzzles immediately.
