### ISSUE TITLE
Feature request : Puzzle type : Light and Shadow

### ISSUE THREAD

**Issue by Carrick22** [robx/pzprjs#274]
Hello ! I'd like to see "Light and Shadow" in the available puzzle types on the puzzlink tool.

Light and Shadow is a relatively simple area/shading puzzle type. I'm providing a link to the rules and a page with puzzles for reference.

Link to rules + an example : http://www.cross-plus-a.com/puzzles.htm#Light%20and%20Shadow
Link to puzzles from Otto Janko : https://www.janko.at/Raetsel/Licht-Schatten/index.htm
Link to gmpuzzles blog wuth puzzles : https://www.gmpuzzles.com/blog/tag/lightandshadow/

Thank you for taking the time to develop such a great web app for puzzlers !

**Comment by robx** [comment]
I agree, this would be great to have!
