### ISSUE TITLE
github actions: fix warnings or disable annotations

### ISSUE THREAD

**Issue by robx** [robx/pzprjs#279]
Pull request diffs currently show warnings unrelated to the change. That's very distracting. We should either fix all the warnings, or disable those annotations while the codebase isn't warning-clean.

<img width="875" alt="Screenshot 2022-11-17 at 21 26 28" src="https://user-images.githubusercontent.com/132113/202552935-d0a7207f-6ba5-41cf-b305-ade48d763137.png">

**Comment by x-sheep** [comment]
I'd like to scope this down to only hide warnings from the `lint` job. The Codecov job will also emit warnings (eventually, not sure why it's not doing it for the Random Colors PR), which I do think deserve attention (even if we don't always fix them)

**Comment by robx** [comment]
I've silenced those redefinition warnings for now.

(In general I think annotations should be relevant to the PR, else they're just noise, but let's see if codecov ever acts up before revisiting that.)
