### ISSUE TITLE
Bug: some turn/flip operations goes wrong when undo-redoing

### ISSUE THREAD

**Issue by subaru-saito1** [robx/pzprjs#394]
I've found bugs in the icebarn editor regarding to the undo/redo of turnflip operations:

**steps to reproduce**

1. put some arrows 
  - https://puzz.link/p?icebarn/3/3/004728/0/2
2. execute boardexec turn left operation 
  - https://puzz.link/p?icebarn/3/3/00a119/8/6
3. execute undo
  - https://puzz.link/p?icebarn/3/3/004728/0/2
4. finally, execute redo, arrow directions go wrong!
  - https://puzz.link/p?icebarn/3/3/00181b/8/6

This happens also turn right, flipX, flipY operation, and this phenomenon also applies to other puzzles with arrows (such as Yajilin, Rome, etc.), and **other symbols (such as vertial/horizontal line in Tateyoko, Juosan).**

I’ve fixed the bug caused by arrow directions (In Pull Request #395).
It turned out to be caused by a double application of converting arrow direction method (`src/variety_common/BoardExec.js:getTranslateDir()`).
That method incorrectly applied to restored correct qdir by redoing.

I confirmed this by the following unit test:

```
it("turn right undo redo", function() {
  var bd = puzzle.board;
  var bd1 = bd.freezecopy();
  bd.operate("turnr");
  var bd2 = bd.freezecopy();
  puzzle.undo();
  puzzle.redo();
  assert_equal_board(bd, bd2);
  puzzle.undo();
  assert_equal_board(bd, bd1);
  assert.equal(puzzle.check()[0], null);
});
```

But the following puzzles still report assertion errors (due to the special symbol, such as vertical/horizontal line, diagonal line, etc.)
So these must be fixed.

- *Amibo*
- *Gokigen*
- *Juosan*
- *Kinkonkan*
- *Ladders*
- *Lollipops*
- *Loopsp*
- *Pentopia*
- *Pipelink*
- *Pipelinkr*
- *Reflect*
- *Slalom*
- *Slashpack*
- *Tatamibari*
- *Tateyoko*
- *Wagiri*

**Comment by x-sheep** [comment]
Thanks for reporting the issue. I think a better way to fix the issue is to avoid using the `set` functions, and just modifying the properties directly without creating an operation.

**Comment by x-sheep** [comment]
I've added your test, and deployed a fix.
