### ISSUE TITLE
aho: Question mark clues do not validate shape

### ISSUE THREAD

**Issue by x-sheep** [robx/pzprjs#399]
We should check if existing aho puzzles make use of this problem before fixing this.

![image](https://user-images.githubusercontent.com/7021451/225344255-8fd5e765-ba19-4734-8088-3fc57c202ad2.png)

**Comment by m-ender** [comment]
There don't seem to be any vanilla Ahos in the DB that use question mark clues. The only one I can see is this variant Aho, which (judging by the rules explanation on the blog) expects question mark clues to work as intended, not as currently implemented: https://ihnnpuzzles.blogspot.com/2020/12/puzzle-272-filling-space-aho-fillomino.html
