### ISSUE TITLE
Implementation of Building Walk doesn't match original rule

### ISSUE THREAD

**Issue by bay-puz** [robx/pzprjs#439]
[According to the Japanese rule of Building Walk](https://github.com/robx/pzprjs/blob/2d5f7e7fdc622b74d9f80573a5503509f5adebff/src-ui/res/rules.ja.yaml#L2), the building has floors from the 1st to the largest number on the board.
This rule comes from the original rule, i.e., the rule in Nikoli vol. 174.

In contrast, pzpr (and English rule) allows to go up a higher floor.
Therefore I would like you to change the implementation.

**Comment by x-sheep** [comment]
This was reported earlier in pzprxs's issue board. https://github.com/x-sheep/pzprjs/issues/7. I'll leave this issue up as well.

I've tried several times to modify the answer checker, but I've had no luck 😟 It may be required to delete and rewrite the entire answer checker from scratch.
