### ISSUE TITLE
Deployments no longer working

### ISSUE THREAD

**Issue by x-sheep** [robx/pzprjs#496]
@robx 

The deploy step fails with the message `autodeploy disabled`.

Example: https://github.com/robx/pzprjs/actions/runs/6222746645/job/16923798998

**Comment by robx** [comment]
Oops, seems the machine was rebooted due to some reason, and `/run/autodeploy-enabled` went missing because it's on a `tmpfs`. Should work again for now, could you check?

(Will think about making it more robust.)

**Comment by x-sheep** [comment]
https://github.com/robx/pzprjs/actions/runs/6222746645/job/17213343270

It currently fails with:
```
Identity added: (stdin) (deploy@puzzlink)
building the system configuration...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by robx** [comment]
Hmm. Looks like something less obvious is also wrong, will need to do some digging to properly figure that out but I won't get around to that until next week.

I redeployed manually just now -- there's a vague chance that this reset things to a state where the ssh config works again.

**Comment by x-sheep** [comment]
Autodeploying seems to work now, but it's possible that this is only the case because the actual commit being deployed was already present on the server.

**Comment by robx** [comment]
Ok, let's keep this open and see if it works next time.

**Comment by x-sheep** [comment]
I just did another deployment, and it seems to work fine. I think we can close this.
