### ISSUE TITLE
Unable to read "git.json" file

### ISSUE THREAD

**Issue by fffpuzzle** [robx/pzprjs#525]
When I cloned the repository and tried `make` to build, I got this error, and can' find the `git.json` file.
```
\pzprjs > make
npm run-script build

> pzpr@0.12.0 build
> eslint --cache --quiet src src-ui && grunt default

Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "git.json" file (Error code: ENOENT).
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
make: *** [build] error 3
```
Where can I find the file?

**Comment by fffpuzzle** [comment]
It seems that git-hash.sh does not work on windows powershell

**Comment by x-sheep** [comment]
The `git.json` file isn't critical when developing. You can make the file yourself and fill it with something like this:

```json
{
  "hash": "00000000"
}
```

**Comment by fffpuzzle** [comment]
This works for me. Thank you!
