### ISSUE TITLE
Sticky trial mode when erasing the answer

### ISSUE THREAD

**Issue by alicebob** [robx/pzprjs#57]
I tried this with a yajilin:

- start solving
- enter trial mode
- draw a few more lines
- erase the answer
- some lines will be drawn in trial mode again

![image](https://user-images.githubusercontent.com/621306/62209159-1bd7b380-b399-11e9-88cd-d8acb917a8b3.png)

**Comment by robx** [comment]
I believe this is fixed now. (Both by cleanly aborting trial mode then clearing the board when doing "Erase Answer" during trial, and by hiding the "Erase Answer" button in trial mode.)

**Comment by alicebob** [comment]
thanks!
