### ISSUE TITLE
Export URL is broken in some puzzles

### ISSUE THREAD

**Issue by x-sheep** [robx/pzprjs#90]
Attempting to output an URL results in the following error:
```
TypeError: this.urlanchor is null
PopupMenu.js:386:2
```
This happens when attempting to open the Export URL popup. Clicking "Export URL" again does work, but pressing one of the Output buttons reports the same error every time.

For me, this occurs in Heyawake when running the editor from [an empty url](https://puzz.link/p?heyawake) (but not when opening a heyawake_edit url). I've seen reports on Twitter that this sometimes happens with other puzzles (such as Double Choco), but I can't reproduce it.

**Comment by robx** [comment]
Thanks for the report. I see now what happens: It's updated Javascript running against stale HTML. I've wiped the server cache now, so after a refresh this should now be fixed client-side. I don't see a way to force that any better, or really how to avoid such problems entirely in the future... Will think about it.

**Comment by robx** [comment]
I'm going to assume this was fixed now -- feel free to reopen if the problem persists!
